Done : - Commited in coq 8.2 branch the patch for the lexer allowing again a smooth treatment of the May modality. - Subsequent change in ssr - blindly patched the implicit arg machinery to comply with Hugo's commit on recursive notations. - Patched pat_of_ssrterm which was generating forbidden identifers with comments.
Good news : ssrcoq compiles (again) and the libraries of the archive
up to binomials (this is more than the released libraries :-))

To Do (at least...) : 
- Fix the bad news above...

- Experiment a global replace of Prenex Implicits
with the bracket implicits of Coq 8.2 (ie. modify the vernac extend for
backward compat)


May be bad news : slight changes were needed in .v files
- in eqtype.v I had to add an @ in the first  anonymous field of the
subType record. But this seems fair.

- in finfun l.210 (card_family) : two goals arising from a !repeated
  conditional rewrite are  now generated in reverse order.

- in finset l. 984 (imsetU), the multirule in 
 rewrite tS (andbT, subsetUl, subsetUr) // andbT.
 now captures what was before treated by the last andbT and the command becomes:
 rewrite tS (andbT, subsetUl, subsetUr) //.

- in binomial l.105 : (bigD1 Fp1) fails and needs an explicit
conversion to work.
 
Definitly bad news : 
- in binomial l.106 : rewrite [mFpM _  _]mFp1 raises
Error: pattern (mFpM _SSR_pat_var_1 _SSR_pat_var_2)
(fun o : 'I_p => [eta mFpM o]) only matches term with bound variables

Of course I suspect my patch for pat_of_ssrterm, but I really don't
know what to do for the moment...



git-svn-id: svn+ssh://scm.gforge.inria.fr/svnroot/coqfinitgroup/trunk@1102 305884b8-be16-0410-aa53-a3be2363cef1