*fixed : - the swap in unfold switches - Matthieu has corrected the pb with anonymous fields in records
*understood:
- the pb with move. comes from the new entry in Coq's g_tactic.ml4
 for 'move after', which introduces a terminal... may be ask for
 a change in Coq? :-)

*not fixed:
- the commented line about rewrite ... with.. (binders?)
- the May flag (eg. in rewrite items) raises an
Error: Metavariables allowed only in patterns.



git-svn-id: svn+ssh://scm.gforge.inria.fr/svnroot/coqfinitgroup/trunk@1087 305884b8-be16-0410-aa53-a3be2363cef1